### ISSUE TITLE
Syntax Coloring Wrong for PHP tags in attributes

### ISSUE THREAD

**Issue by jakob** [textmate/html.tmbundle#3]
The HTML bundle incorrectly highlights the syntax whenever I use inline PHP code inside a tag as an attribute, and I don't quote it. (quotes are optional in HTML5)

Example

    <!DOCTYPE HTML>
    <html>
    <head>
    	<meta charset=utf-8>
    </head>
    <body>
    	<?$p=0?>
    	<p id=paragraph<?=++$p?>>
    		This is test paragraph <?=$p?>.
    	</p>
    	<p id="paragraph<?=$p++?>">
    		This is test paragraph <?=$p?>.
    	</p>
    	<p id=paragraph<?=++$p?>>
    		This is test paragraph <?=$p?>.
    	</p>
    	<p id="paragraph<?=$p++?>">
    		This is test paragraph <?=$p?>.
    	</p>
    </body>
    </html>

Syntax highlighting breaks until the next quote occurs.

**Comment by infininight** [comment]
This was corrected at some point when transitioning to the new PHP grammar.
