### ISSUE TITLE
HTML `=` punctuation scoped as text

### ISSUE THREAD

**Issue by bobrocke** [textmate/html.tmbundle#38]
OS X version: 10.10.3
TextMate version: 2.0b7.1
The (code) language you’re working in: HTML in TWIG

The `=` in `class="class-name"` has a scope of `meta.tag.inline.any.html` when it would seem that `punctuation.something` is more appropriate.

**Comment by infininight** [comment]
Corrected, now has a scope of `punctuation.separator.key-value.html`.
