### ISSUE TITLE
"Refresh Running Browser(s)" fails silently

### ISSUE THREAD

**Issue by rdwampler** [textmate/html.tmbundle#41]
This script requires that "Allow Javascript from Apple Script" to be enable under the Develop menu in Safari on OS X El Captain. 

If ran in the terminal the following error is shown: 
```
Refresh Running Browsers.scptd/: execution error: Safari got an error: You must enable the 'Allow JavaScript from Apple Events' option in Safari's Develop menu to use 'do JavaScript'. (8)
```

It would be nice to report this to the user.

**Comment by infininight** [comment]
Seems Script Editor broke opening the script in both 10.11.4 and 10.10.4, had to boot from an old drive to get a [copy of the script](https://gist.github.com/infininight/b9e70a8f950dcd5ed248cff44e2ad9e8).

The only mention of this issue I can find on Google is Keyboard Maestro working around the issue by detecting when it fails and presenting a dialog.

**Comment by feekApp** [comment]
Hi,
the issue that CMD-R is not working anymore is related to the (security) update of OSX 10.11.5. I just booted from my old system (OSX 10.11.4, made just before updating) and it was working OK.

As mentioned on the TM mailing list and on the [Keyboard Maestro forum](https://forum.keyboardmaestro.com/t/safari-actions-not-working/3765) the (temporarily) solution:

- Enable the Develop menu in Safari if not already enabled in Safari’s Advanced preferences.
- Enable Allow JavaScript from Apple Events in the Develop menu.

**Comment by infininight** [comment]
Just deployed a fix for this issue. Got around it by getting and setting the URL of the current tab without the use of javascript. I also included a plain text version of the script just incase Script Editor goes wonky again.

**Comment by rdwampler** [comment]
Thanks @infininight!

**Comment by feekApp** [comment]
Also thnx @infininight from here!

One question, is there a way to let it also work with Firefox (Developer)? I use both for develop.

**Comment by feekApp** [comment]
hi @infininight,

now I have the same issue as mentioned [here](http://textmate.1073791.n5.nabble.com/HTML-refresh-running-browsers-issue-on-clean-install-td29767.html)

**Comment by infininight** [comment]
Well somehow the script I edited last night already wouldn't open in Script Editor… so that's good, glad a saved a text copy.

@feekApp I've added Firefox Developer. Can reproduce your second issue… not sure why it worked before and not now… Seems to allow me to remove Firefox but not Camino, perhaps because of the manner of scripting?

**Comment by feekApp** [comment]
Hi @infininight,

Thnx again for digging into this issue!

But unfortunately I have still the popup window for Chrome and Camino (both not installed, see [here](http://textmate.1073791.n5.nabble.com/HTML-refresh-running-browsers-issue-on-clean-install-td29767.html)).  Ans also FF-dev is not reloading :(

I restarted my Mac, reload the HTML-bundle etc. but no effect. Am I doing something wrong?

**Comment by infininight** [comment]
The popup issue isn't fixed, the Firefox Dev should be working. But I think this is just going to have to be split back into multiple scripts to work reliably again, Applescript really makes it a pain to do anything conditional like this, trying to trick it into submissions appears to be a losing proposition.

**Comment by feekApp** [comment]
OK, thnx.
I'll be patient!

**Comment by ertoorule** [comment]
leave default browser! and comment out others! work for me!
like this! (My default browser is canary)

#!/usr/bin/env osascript

-- if application "Safari" is running then
--   tell application "Safari"
--     set sameURL to URL of current tab of front window
--     set URL of current tab of front window to sameURL
--   end tell
-- end if

try
	tell application "Finder"
		name of application file id "com.google.Chrome.canary"
	end tell
	if application "Google Chrome Canary" is running then
		run script "
			tell application \"Google Chrome Canary\"
				reload active tab of window 1
			end tell
		"
	end if
on error
	-- do nothing
end try

-- try
--   tell application "Finder"
--     name of application file id "com.google.Chrome"
--   end tell
--   if application "Google Chrome" is running then
--     run script "
--       tell application \"Google Chrome\"
--         reload active tab of window 1
--       end tell
--     "
--   end if
-- on error
--   -- do nothing
-- end try

-- try
--   tell application "Finder"
--     name of application file id "org.mozilla.firefox"
--   end tell
--   if application "Firefox" is running then
--     run script "
--       tell application \"Firefox\" to activate
--       tell application \"System Events\"
--         tell process \"Firefox\"
--           keystroke \"r\" using {command down}
--         end tell
--       end tell
--     "
--   end if
-- on error
--   -- do nothing
-- end try

-- try
--   tell application "Finder"
--     name of application file id "com.apple.SafariTechnologyPreview"
--   end tell
--   if application id "com.apple.SafariTechnologyPreview" is running then
--     run script "
--       tell application id \"com.apple.SafariTechnologyPreview\"
--         set sameURL to URL of current tab of front window
--         set URL of current tab of front window to sameURL
--       end tell
--     "
--   end if
-- on error
--   -- do nothing
-- end try

-- try
--   tell application "Finder"
--     name of application file id "com.operasoftware.Opera"
--   end tell
--   if application id "com.operasoftware.Opera" is running then
--     run script "
--       tell application \"Opera\"
--         reload active tab of front window
--       end tell
--     "
--   end if
-- on error
--   -- do nothing
-- end try
