### ISSUE TITLE
Cannot decompile "Refresh Running Browser(s)" script to edit it

### ISSUE THREAD

**Issue by rdwampler** [textmate/html.tmbundle#42]
When running `osadecompile Refresh\ Running\ Browsers.scptd/` I get the following error:
```
osadecompile: Refresh Running Browsers.scptd/: e.g.,: specifier asked for the 3rd, but there are only 2. Basically, this indicates a run-time resolution error.
```
I believe this error is because to decompile the script the command is looking for the source in another folder that is not part of the repo. Is possible to add the original source file in addition to the compiled binary?

**Comment by feekApp** [comment]
Hi,
it seems related to the OSX 10.11.5 update today. Before the update (on 10.11.4)  everything works as expected.

Besides Safari also Firefox has the same issue.

Regards,
Feek

**Comment by infininight** [comment]
Hmm, that's rather annoying, but it appears to not be anything related to the upload of the script. I made the last edit and thus have the actual not-downloaded file and it won't open here either. They must have broken something with one of the 10.11 point updates. Will try to extract the actual script.

**Comment by infininight** [comment]
Merging discussion into #41, copy provided there.
