### ISSUE TITLE
HTML "script" tags improperly scoped

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#52]
_From @smlombardi on March 7, 2017 19:57_

Steps to Reproduce:

Please see attached screenshots:  the `=` for attributes is not the same color for `script` tags as all other html tags.

This is because all other tags they are scoped `meta.tag.inline.any.html`, whilst script tags are only `text.html.basic`. This is a bug IMHO.

Script tag:
![screen shot 2017-03-07 at 2 53 38 pm](https://cloud.githubusercontent.com/assets/835148/23675150/5ffddbc6-0346-11e7-9a8b-d6c99e7f3b57.png)

Sample other tag:
![screen shot 2017-03-07 at 2 54 07 pm](https://cloud.githubusercontent.com/assets/835148/23675162/6d6895ee-0346-11e7-8f7b-a7fb7f731a0a.png)

_Copied from original issue: Microsoft/vscode#22176_

**Comment by infininight** [comment]
Overhauled the matching of this and style tags, now uses the meta.embedded scope with more exacting scoping overall.
