### ISSUE TITLE
[HTML/JS] Syntax highlighting is wrong when </script> is commented out

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#53]
_From @mkszepp on March 25, 2017 22:9_

- VSCode Version: 1.10.2 / 1.11.0-insider
- OS Version: Windows 10

The syntax highlighting fails when `// ]]></script>` is in the same line.

![example](https://cloud.githubusercontent.com/assets/19845290/24326440/aa781fba-11ae-11e7-926b-91e897f3ec26.png)

<html>

    <head>
        <title>Example</title>
    </head>
    
    <body>
    
        <script type="text/javascript">// <![CDATA[
        
            var a = 'xy';
        
        // ]]></script>
    
    </body>

</html>

_Copied from original issue: Microsoft/vscode#23221_

**Comment by aeschli** [comment]
This has to to with the single line comment on line `// ]]></script>`.
The embedded JS parser will skip the whole line.

This has to do with the way TextMate embeds grammars. The embedded grammar doesn't know of the outer language end tags. The only fix would be not embed the regular JS grammar but have a special JS grammar just for source embedded in HTML.

**Comment by sorbits** [comment]
It might also be possible to solve by injecting a rule into the embedded scope that matches comments until a potential script end tag, though that solution would probably only work in TextMate, as I don’t think any of the other editors that use these grammars support injection.

**Comment by infininight** [comment]
Corrected in 18afae7e5712a0872d0863abb7e4b7f482578aba, there was already an exception added to correct this but it was accidentally nullified due to a `comment.line` match change in the JavaScript grammar.
