### ISSUE TITLE
Syntax highlighting broken when PHP code is mixed inside Javascript

### ISSUE THREAD

**Issue by ouatataz** [textmate/html.tmbundle#54]
Dear all,

Since the later update of the bundle, syntax highlighting is broken when php code is mixed inside js.
Try : 
`	<script type="text/javascript">
		<?php echo $ok; ?>
	</script>
`

And you will see what's happening.
Is there a way to fix this ?

Thanks in advance

**Comment by infininight** [comment]
Sorry I overlooked changing this, fixed in textmate/php.tmbundle@1d91862a3d118827aa4c0fb57672625a704410c0. Your bundle should update within a few hours automatically, thanks for reporting!

**Comment by ouatataz** [comment]
Thx for your efforts and the feedback

**Comment by rinogo** [comment]
Could a similar fix help with https://github.com/textmate/html.tmbundle/issues/102
