### ISSUE TITLE
Syntax highlighting broken when <script> tag has no 'type="text/javascript"' attrib

### ISSUE THREAD

**Issue by hanns** [textmate/html.tmbundle#55]
Title says it.

**Comment by infininight** [comment]
There have been some improvements to this now. Please recheck and if it is not fixed re-open this issue with a code sample.

**Comment by hanns** [comment]
@infininight: Yeah, updated it, and still the same.

<img width="551" alt="screen shot 2017-04-02 at 12 44 27 am" src="https://cloud.githubusercontent.com/assets/213692/24584488/b0e815fa-173d-11e7-9a73-a643625449df.png">

````
<script>
	// no attrib
	console.log('syntax highlight broken =(...')
</script>
<script type="text/javascript">
	// has attrib
	console.log('syntax highlight not broken! =)...')
</script>
<style>body { font-weight: bold; }</style>
<body>
	<p style="font-size: bigger;">everything else works fine</p>
</body>
````
