### ISSUE TITLE
<script> without type=text/javascript is no longer highlighted as JavaScript

### ISSUE THREAD

**Issue by JosephPecoraro** [textmate/html.tmbundle#56]
Recently the HTML bundle stopped syntax highlighting JavaScript inside of a plain `<script>` tag.

Test case:

```html
<!-- Not highlighted -->
<script>var x = 1</script>

<!-- Correctly highlighted -->
<script type="text/javascript">var x = 1</script>
```

I would expect `<script>`, `<script type="module">`, and `<script type="text/javascript">` to all behave the same way. These are each valid forms of specifying JavaScript content. See [HTML Script Element - Type Attribute](https://html.spec.whatwg.org/#attr-script-type).

Notes: I suspect https://github.com/textmate/html.tmbundle/commit/56362f15143dfd21b1edd5842ef1a7d26787214f may be related, since it landed just a few days ago.

**Comment by JosephPecoraro** [comment]
Also text inside of a `<script type="text/javascript">` is getting indented where I don't think it was getting indented previously. If I want to write code like:

```html
<script type="text/javascript">
function foo() {
    alert(1);
}
</script>
```

I end up with:

```html
<script type="text/javascript">
    function foo() {
        alert(1);
    }
    </script>
```

Namely the closing tag does not dedent, but also I'm getting early indentation that I have to constantly be getting rid of. If this is a separate issue I can file it separately

**Comment by ianlotto** [comment]
+1

**Comment by infininight** [comment]
Corrected, thanks for the note. Wasn't aware the type was optional when I did the previous commit.

@JosephPecoraro I've corrected the tag indentation as well with a workaround due to the mixed scoping at play. I do however increase/decrease the indent level with the tags as that falls more in line with how other block-type tags behave in the grammar.
