### ISSUE TITLE
Latest release on longer recognizes the content of script element with type="text/html" as html

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#62]
_From @dancvogel on May 4, 2017 18:59_

- VSCode Version: Code 1.12.0 (72672be0b7d3eef0784077b880615f91b7ec85aa, 2017-05-04T16:18:34.633Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|code-beautifier|michelemelluso|1.7.2|;

Latest release on longer recognizes the content of script element with type="text/html" as html. It's now coloring the entire block as a single color and not a different color for the element name, and for attribute, and for attribute value. 
![capture](https://cloud.githubusercontent.com/assets/5480284/25720276/23b4831a-30c1-11e7-8c6b-c0e648ded90a.PNG)

---

Steps to Reproduce:

1.
2.

_Copied from original issue: Microsoft/vscode#25920_

**Comment by Borongaj** [comment]
Same here :

VSCode 1.12.1
OS Version: macOS Sierra 10.12.4

**Comment by infininight** [comment]
Fixed in 59ce43d89ff12d589a35583dc633c1d746c37189.
