### ISSUE TITLE
Highlight error

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#68]
_From @cpa-level-it on April 28, 2017 7:24_

I discovered an error with the syntax highlighting of HTML code.
If we have a custom tag that starts with *script* followed by a dash ex  `<script-module>`. The text after the *script* part will be highlighted in red and the rest of the file will not be correctly highlighted.

See this screenshot 

![image](https://cloud.githubusercontent.com/assets/9820390/25518147/dc32ed56-2bf2-11e7-9955-a4fbc12aa133.png)

```html
<split-pane-container>
  <script-module></script-module>
</split-pane-container>
```

Steps to Reproduce:

1. Type in a tag that starts with *script* followed by a dash eg `<script-module></script-module>`
2. The file isn't correctly highlighted

_Copied from original issue: Microsoft/vscode-html-languageservice#10_

**Comment by infininight** [comment]
Added in 09599f593af853f0e7dc2b0a456f79f1c044c8f0. Now gives a scope of `meta.tag.custom` to any custom tag.

cc @cpa-level-it
