### ISSUE TITLE
Angular ngif less than syntax highlighting

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#70]
_From @mterczynski on July 17, 2017 23:41_

![image](https://user-images.githubusercontent.com/27309340/28294388-190bddd6-6b5a-11e7-830b-3116c486e9a1.png)

"Greater than" works fine:
![image](https://user-images.githubusercontent.com/27309340/28294408-4738802e-6b5a-11e7-85e9-56286939d0a8.png)

_Copied from original issue: Microsoft/vscode#30891_

**Comment by infininight** [comment]
Fixed in 0ab9f1474ab07d604012a2ab142ac16877baed89.

**Comment by bertdebleser** [comment]
I have this problem whats the fix ?

**Comment by JinjinM** [comment]
I also face the same problem.

**Comment by BrotherCrayon** [comment]
Has this actually been fixed? I am having the same issue. the '<' symbol appears in red with no other indications as to what is wrong.
