### ISSUE TITLE
Html script closing-tag not detected when occurs immediately after 2 slashes

### ISSUE THREAD

**Issue by SDP190** [textmate/html.tmbundle#72]
Hi, I found a bug, with the html grammar in VS Code, when you place a closing script-tag in the same line immediately after 2 fwd slashes, as:
`<script>  //</script>`
the grammar will not detect the closing tag, and will display it with wrong color, see images.

(I'm not sure if the issue is related only to [vscode-textmate](https://github.com/Microsoft/vscode-textmate), or it belongs to [textmate/html.tmbundle)](https://github.com/textmate/html.tmbundle).

VS Code:
![sample](https://user-images.githubusercontent.com/16751213/27235025-2fea2a02-528d-11e7-9132-4acd6ab80a2c.JPG)

Visual Studio 2015:
![capture](https://user-images.githubusercontent.com/16751213/27235056-4b630e20-528d-11e7-9479-567e0921b026.JPG)

---
- VSCode Version: Code 1.13.1 (379d2efb5539b09112c793d3d9a413017d736f89, 2017-06-14T18:21:47.485Z)
- OS Version: Windows_NT ia32 10.0.15063

---

Steps to Reproduce:

1. Open any html document with VSCode.
2. Insert a script element in the document, and place the script's closing-tag immediately after 2 fwd slashes.

**Comment by infininight** [comment]
This does not happen in TextMate with the current bundle. Will need to talk with the VSCode devs to see if it is up-to-date or a difference in the parsing engines.
