### ISSUE TITLE
Any plans to highlight angularjs 1.x syntax in html?

### ISSUE THREAD

**Issue by urielzen** [textmate/html.tmbundle#73]
In visual studio when you have angular1.x attributes like ng-show="" or others similar the attributes are highlighted with a orange/pink color, as well as the mustache bindings like {{myModel.someProp}}.

Just like in VisualStudio, I hope this feature could be implemented in VSCode.

I wish I was working with angular2/4 already but my company is stuck with 1.x for the long run.
Thanks

**Comment by infininight** [comment]
The attributes might not be terribly hard to do, as they wouldn't conflict much at first glance. But the mustaches would require either a injection grammar or a new grammar variant as in normal HTML `{{}}` are meaningless. Either way this is would need to be in a separate bundle so I'm going to close this issue.
