### ISSUE TITLE
Invalid syntax highlighing of <!----------blablabla-----------> in .html file

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#75]
_From @luqimin on September 7, 2017 14:44_

as mentioned in the title..

_Copied from original issue: Microsoft/vscode#33944_

**Comment by aeschli** [comment]
_From @roblourens on September 7, 2017 17:36_

I see that it messes up colorization. Not sure if it's invalid or what:

![image](https://user-images.githubusercontent.com/323878/30176411-305a12c0-93b7-11e7-9caa-a07e03ce3e97.png)

**Comment by aeschli** [comment]
_From @emackey on September 7, 2017 19:40_

See also:

https://stackoverflow.com/questions/26600092/why-are-double-hyphens-invalid-in-html-comments

https://stackoverflow.com/questions/1850439/double-hyphen-in-script-makes-firefox-render-strangely

**Comment by aeschli** [comment]
_From @iMahesh on September 7, 2017 20:43_

@luqimin if you a leave `space` on both sides of `--------blablabla---------` just like `<!-- --------blablabla--------- -->` instead of `<!----------blablabla----------->` it works perfectly well(It's a best practice as well). 
It'll also work if you add one more `-` on the right-hand side of the `blablabla`, just in case if you don't want to leave any space in-between. 

I wouldn't recommend typing `<!-- -->` manually to comment lines. better to use `Ctrl+/` to avoid any DOM rendering issues.

[SOURCE](https://www.w3.org/TR/REC-xml/#sec-comments)

**Comment by aeschli** [comment]
_From @yume-chan on September 8, 2017 5:27_

Multiple hyphens in comments are valid in [HTML5 standard](http://w3c.github.io/html/syntax.html#comments):

> ### 8.1.6. Comments
> **Comments** must have the following format:
> 1. The string "`<!--`"
> 2. Optionally, text, with the additional restriction that the text must not start with the string "`>`", nor start with the string "`->`", nor contain the strings "`<!--`", "`-->`", or "`--!>`", nor end with the string "`<!-`".
> 3. The string "-->"

In fact, according to the parsing rules, `<! >`, `<!-- <!-- -->` and `<!-- --!>` are parse errors but recoverable and also represents HTML comments.

Of course, they are invalid in XML standard, but HTML is not XML.

**Comment by infininight** [comment]
This has now been updated to match the current HTML5 spec.
