### ISSUE TITLE
Support for text/paperscript in html.json

### ISSUE THREAD

**Issue by perrydyball** [textmate/html.tmbundle#76]
Similar Issue re text/babel : https://github.com/Microsoft/vscode/issues/11781 can you please add text/paperscript to the html.json to support syntax highlighting for paper.js in VSCode.

I have applied locally and everything appears to work satisfactorily.

**Comment by kflorence** [comment]
+1

**Comment by ivanpk** [comment]
Also applied change locally and seeing no error. Would be great to have as a default!

**Comment by RonHouben** [comment]
Hereby the direct to the solution:
[https://github.com/Microsoft/vscode/issues/11781#issuecomment-301372638](url)

And the text from  [@phocks](https://github.com/phocks)

> For reference on macOS you need to right-click > Show package contents in your Applications folder then browse to /Contents/Resources/app/extensions/html/syntaxes/html.json

Then find where it says (javascript|ecmascript) in the file and change it to (javascript|ecmascript|babel) in both places in that line of code.

**Comment by infininight** [comment]
Support for this was added in a723f08ebd49c67c22aca08dd8f17d0bf836ec93, not sure if it is present in VSCode yet.

**Comment by josephemorgan91** [comment]
Link to solution in previous post isn't working, issue is closed because "support was added" in 2018, but the issue doesn't seem to be solved. Still no paperscript syntax highlighting.

Anyone have any idea what's going on?

**Comment by chwdy** [comment]
I think it didn't solve the problem, the fix https://github.com/textmate/html.tmbundle/commit/a723f08ebd49c67c22aca08dd8f17d0bf836ec93
just add support for "babel". not for paperscript

**Comment by josephabbey** [comment]
Why don't you put a setting for mime-type association or something and then if someone had:
```json
{
  "text/python": "python"
}
```
it would use the python functionality inside of that tag, or the same for paperscript.
