### ISSUE TITLE
Remove entity higlights from tag attributes

### ISSUE THREAD

**Issue by jo-pol** [textmate/html.tmbundle#81]
The example below shows two examples of both red and blue highlights, one pair in the attribute values, one pair between the tags. The highlights in the attribute value should be removed.

```html
<a href="?x=y&a=b&amp;c">x & y &amp; z</a>
```

This is different from entities in [comments](https://github.com/textmate/html.tmbundle/pull/49#issuecomment-264711812), that might be temporarily switched off code, I won't meddle with that discussion.

**Comment by infininight** [comment]
Fixed in 69a40fef0138f93c625f67cd931d135014b740a7.
