### ISSUE TITLE
html highlight is bugged when next tag starts with same prefix

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#84]
HTML syntax highlight is broken when the next html tag starts with the same prefix of the previous one. see attached image.

![image](https://user-images.githubusercontent.com/984628/40124756-8b518a40-5929-11e8-8385-659d51b9745f.png)

Same with:

`<div><i><input></i></div>`.

**Comment by aeschli** [comment]
_From @vscodebot[bot] on May 16, 2018 14:55_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Closing HTML tag not highlighting in PHP files. (#38391)](https://www.github.com/Microsoft/vscode/issues/38391)

**Comment by aeschli** [comment]
@phra I'm not able to reproduce this. Can you give full file example? The editor is in HTML mode, right (not PHP or TS React)?

**Comment by aeschli** [comment]
_From @phra on May 17, 2018 10:15_

@aeschli just create a new project with the following html: `<div><i><input></i></div>`.

is maybe related to the fact that the inner tag is self-closing?


![image](https://user-images.githubusercontent.com/984628/40171557-df89c65c-59cb-11e8-8360-3191c364cf4b.png)

**Comment by phra** [comment]
original issue: https://github.com/Microsoft/vscode/issues/49982

**Comment by infininight** [comment]
Corrected, thanks!
