### ISSUE TITLE
Incorrect Javascript function highlighting in HTML tag

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#86]
_From @aerchit on June 28, 2018 8:13_

 

- VSCode Version: 1.24.1
- OS Version: windows 10 64bits

![visual studio code](https://user-images.githubusercontent.com/17045080/42021507-65e969fe-7aed-11e8-9248-a1296315e0f5.png)

Steps to Reproduce:

1. insert this in html body
`<p onclick="add('p<br>');" >click me</p>`

2. use any color theme. **All of them cannot highlight correctly,** but Sublime Text can.

Does this issue occur when all extensions are disabled?: Yes

_Copied from original issue: Microsoft/vscode#53219_

**Comment by infininight** [comment]
Corrected in 0ab9f1474ab07d604012a2ab142ac16877baed89.
