### ISSUE TITLE
Tag closing baracket no longer gets `punctuation.definition.tag.html` scope

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#89]
With the latest changes, the closing bracket `>` only gets the `text.html.basic meta.tag.custom.end.html"` scope. It used to be `text.html.basic meta.tag.any.html punctuation.definition.tag.html`

There are many theme that look for the for `punctuation.definition.tag` tags.
(defining a color rule for `meta` scopes is not recommended as meta tags typically define a range.

**Comment by infininight** [comment]
Good catch, a mis-numbered capture. Checked all the other matches and I think that's the only punctuation match that got mis-numbered.
