### ISSUE TITLE
HTML custom elements incorrectly formatted as errors

### ISSUE THREAD

**Issue by ericbirdsall** [textmate/html.tmbundle#90]
It looks like the syntax highlighter is incorrectly highlighting custom elements as errors. I looked through the recent commits but couldn't find any change related to this issue. To reproduce, open an HTML document in Textmate and paste in the following code:
```
<html>
	<myElement>
	</myElement>
</html>
```
`myElement` is highlighted.

**Comment by infininight** [comment]
The bundle was exceedingly loose in what it supported, it has now been updated to the HTML 5 spec. Custom elements are allowed but must contain one or more `-` characters to prevent future collisions with element additions.

https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements-core-concepts
