### ISSUE TITLE
custom 'html' tags are in red color

### ISSUE THREAD

**Issue by aeschli** [textmate/html.tmbundle#92]
_From @VladimirAmiorkov on August 15, 2018 12:24_

 

- VSCode Version: 1.26.0 (1.26.0)
- OS Version: macOS High Sierra 10.13.6 (17G65)

Steps to Reproduce:

1. Download [this](url
https://github.com/telerik/nativescript-ui-samples-angular/blob/master/listview/app/examples/getting-started/listview-getting-started.component.html) html file or create one with "invalid" html tags
2. Open it in the latest version of Vs Code
3. The `GridLayout`, `RadListView` and `StackLayout` are coloured bright red as shown in the screenshot bellow

![screen shot 2018-08-15 at 15 25 01](https://user-images.githubusercontent.com/4989411/44148085-727d13be-a09f-11e8-99cb-d1a100ac6ba7.png)

Does this issue occur when all extensions are disabled?: Yes

I see that this is probably an new feature that has been added to show "invalid" html tags as red but in our realm we are developing [NativeScript with Angular](https://docs.nativescript.org/angular/start/introduction) which includes the creation of our custom html tags which are not part of the standard html tags. Can this be disabled or changed in any way, those tag where not coloured in bright red in the previous version, only in 1.26.0.

_Copied from original issue: Microsoft/vscode#56467_

**Comment by aeschli** [comment]
_From @vscodebot[bot] on August 15, 2018 12:24_

(Experimental duplicate detection)
Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
- [Select to Bracket for HTML tags (#53382)](https://www.github.com/Microsoft/vscode/issues/53382) 
- [Closing HTML tag not highlighting in PHP files. (#38391)](https://www.github.com/Microsoft/vscode/issues/38391) 
- [Emmet suggested full HTML tag inside another tag (#53163)](https://www.github.com/Microsoft/vscode/issues/53163) 
- [\[html\] Add support for custom tag providers for HTML (#2784)](https://www.github.com/Microsoft/vscode/issues/2784)

**Comment by aeschli** [comment]
The coloring of 'invalid' elements makes the grammar very hard to use for HTML-derivatives. I'd vote to remove that enhancement again.

**Comment by EmandM** [comment]
It would be nice to at least have a setting to turn this off, it makes development a lot harder than is necessary.

**Comment by darkyelox** [comment]
It's very annoying see those tags in red color in my NativeScript templates

**Comment by Redsmith24** [comment]
Can anybody please remove this enhancement or can anybody tell me how to remove by myself? Can I edit a specific file in the bundle to remove this?

**Comment by jnorkus** [comment]
This "feature" is a pain to my eyes! Please add a setting.

**Comment by infininight** [comment]
So what I'm looking at doing to correct this is to add a secondary grammar called "HTML (Derivative)" which allows for any tag name. This maintains the integrity of the proper HTML grammar while allowing for template cases where the tag rules are relaxed.

**Comment by infininight** [comment]
This has now been added. The new grammar is exactly the same as the HTML grammar but with the removal of the invalid tag handling. The new tag scoping is retained with a new scope for all tags that would not be valid in a pure HTML context.

Unsure if this will get picked up automatically in the next VSCode release or if it will need special handling perhaps @aeschli can talk to that part.

**Comment by AndreVanKammen** [comment]
<center> is still red, i had to read through 3 closed tickets to get to somewhere I can post that because the original was closed:
https://github.com/Microsoft/vscode/issues/59947
Thanks for wasting a lot of my time to find stuff like this because issues is getting real messy. It won't take long before people just stop bothering to report this stuff. 

And center is not an invalid tag, just obsolete. But it's just easier to use than adding a style to a div that does the same so it will never go away

**Comment by LinuxLikeUnix** [comment]
Was this ever fixed three years ago?

My `<center>` tags are still red.

**Comment by M-Valentino** [comment]
My center tags are still red too.

**Comment by UKhira** [comment]
I had to face this issue with `<center>` tag today. Thought it was syntax error at first. then I recheck, googled and does everything as possible to make it correct. then finally met up with this thumbnail.

This really is an eyesore.

**Comment by AlirezaArifi** [comment]
so,,,, any fixing yet?

**Comment by RetrogradeDev** [comment]
Stil red...

**Comment by Pyonchi** [comment]
`<center>` tag is still red.

**Comment by RetrogradeDev** [comment]
It's because the `<center>` tag is deprecated.
See: [https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center)

**Comment by Pyonchi** [comment]
> It's because the `<center>` tag is deprecated. See: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/center

Oh, thanks for pointing it out, I didn't know about this. I'm still fairly new to HTML/CSS as a whole.

**Comment by sandStoop** [comment]
I don't care if the tag is deprecated. For quick prototyping or if the CSS won't work for no reason, I use such tags. They could just add it into a setting or a switch to flip it on and off. Seeing the red color makes me mad. I use CSS, the right way of centering with text-align doesn't work. It's been just one day of this cruel treatment and I hate it.
