### ISSUE TITLE
`&` and `&&` should not be an error

### ISSUE THREAD

**Issue by thomas-darling** [textmate/html.tmbundle#98]
A single or double ampersand should not be highlighted as an error - it is perfectly valid.
See: https://html.spec.whatwg.org/#character-reference-state

It is often used in binding expressions, as illustrated here, so this bug is quite annoying :-)

![image](https://user-images.githubusercontent.com/6388663/50860384-129fde80-1396-11e9-875f-ff7c07beeb15.png)
Visual Studio Code 1.30.1

**Comment by infininight** [comment]
This does not occur in TextMate so either the grammar version in VSCode is older or not being interpreted the same, will have to take the issue up with them.
